# Generated by Django 5.2 on 2025-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_achievement_userachievement_achievement_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rule',
            field=models.CharField(choices=[('quizzes', 'Total de partidas'), ('points', 'Pontos acumulados')], default='placeholder', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='threshold',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
