# Generated by Django 5.2.1 on 2025-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_playerhistory_finalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='help_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
