# Generated by Django 5.2 on 2025-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_achievement_rule_achievement_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
